services:
  mysql:
    image: mysql:8.0
    container_name: mysql_cadastro_itens
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadastro_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - "3307:3306"
    volumes:
      - mysql_dados:/var/lib/mysql

volumes:
  mysql_dados: